tox.ini: Create

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -1,14 +1,25 @@
 sudo: false
-
+dist: trusty
 language: python
-python:
-  - 3.4
-  - 3.5
-  - 3.6
+notifications:
+  email: false
+
+stages:
+  - name: sentinel
+    if: branch != master OR type = pull_request
+  - test-languages
+  - test-other-versions
+  - moban
+  - name: test-master
+  # if: branch = master AND type = push
+  - name: unsupported
+  # if: branch = master AND type = push
 
 .disable_global: &disable_global
   addons: false
-  cache: pip
+  cache: false
+  env: {}
+  python: false
   before_install: false
   install: false
   before_script: false
@@ -18,32 +29,207 @@ python:
   before_deploy: false
   deploy: false
 
-stages:
-  - name: sentinel
-    if: branch != master OR type = pull_request
-  - test
-  - moban
-  - name: unsupported
-    if: branch = master AND type = push
-
-.check_moban: &check_moban
+.moban: &moban
   <<: *disable_global
   python: 3.6
   stage: moban
-  install: pip install moban
-  script: .ci/check_moban.sh
-  if: branch != master OR type = pull_request
+  install: pip install moban>=0.0.4
+  script:
+    - moban
+    - git diff --exit-code
 
 jobs:
   include:
-    - stage: sentinel
-      # All other jobs will be cancelled if the sentinel job fails
-      <<: *disable_global
-      python: 3.6
-      install: pip install -r requirements.txt ".[alldeps]"
-      script: coala --non-interactive -V
+    # Manually added "language" entries should complete test coverage
+    - stage: test-languages
+      language: lua
+      env: BEARS=lua
+      addons:
+        apt:
+          packages:
+            - luarocks
+
+    - stage: test-languages
+      language: generic
+      env: BEARS=opam INFER_VERSION=0.7.0
+           PATH=$PATH:$HOME/infer-linux64-v$INFER_VERSION/infer/bin
+      addons:
+        apt:
+          sources:
+            - avsm
+          packages:
+            - camlp4-extra
+            - ocaml
+            - opam
+
+    - stage: test-languages
+      # This is in generic image, as language: haskell isnt working yet
+      # https://github.com/coala/coala-bears/issues/1384
+      language: generic
+      dist: xenial
+      env: DIST=xenial BEARS=adhoc BEAR_LIST="ghc-mod hlint"
+      # ghc-mod needs parts of ghc, specifically at least /usr/lib/ghc/settings
+      # ghc-mod needs cabal-install
+      # shellcheck is failing in xenial
+      addons:
+        apt:
+          packages:
+            - cabal-install
+            - ghc
+            - ghc-mod
+            - hlint
+
+    # BEARS=apt_get rather than 'apt' to match key in bear-metadata.yaml
+    - stage: test-languages
+      language: generic
+      dist: xenial
+      env: DIST=xenial BEARS=apt_get DISABLE_BEARS=shellcheck
+      addons:
+        apt:
+          packages:
+            - chktex
+            - cppcheck
+            - devscripts
+            - flawfinder
+            - indent
+            - libperl-critic-perl
+            - libxml2-utils
+            - mono-mcs
+            - php7.0-cli
+            - phpmd
+            - php-codesniffer
+            - verilator
+
+    - stage: test-languages
+      language: generic
+      dist: xenial
+      env: DIST=xenial BEARS=adhoc BEAR_LIST="bakalint default-jre"
+
+    - stage: test-languages
+      language: generic
+      env: DIST=trusty BEARS=adhoc BEAR_LIST=astyle
+      addons:
+        apt:
+          sources:
+            - sourceline:  # astyle
+                deb http://ppa.launchpad.net/cs50/ppa/ubuntu trusty main
+              key_url:
+                https://keyserver.ubuntu.com/pks/lookup?op=get&search=0x5BDA2E974A0E822C
+          packages:
+            - astyle
+
+    # Additonal manual entries
+    - stage: test-other-versions
+      os: windows
+      language: bash
+      python: 3.6.8
+      env:
+        BEAR_LIST="astyle cppcheck xmllint"
+        TOX_TEST_SELECTORS=pip-noreqs-npm-gem-go-perl-php-java8-adhoc
+      cache:
+        directories:
+          - C:/nuget_http_cache/
+          - C:/choco_cache/
+          - C:/pip_cache/
+      before_install:
+        - bash --version
+        - powershell -c "$PSVersionTable"
+        - powershell -c 'Set-MpPreference -DisableRealtimeMonitoring $true'
+        - powershell -c 'Set-MpPreference -DisableArchiveScanning $true'
+        - powershell -c 'Set-MpPreference -DisableBehaviorMonitoring $true'
+
+        - export NUGET_HTTP_CACHE_PATH=/C/nuget_http_cache
+        - export CHOCO_CACHE_DIR=/C/choco_cache
+        - export PIP_CACHE_DIR=/C/pip_cache
+
+        - export TOXENV=py36-${TOX_TEST_SELECTORS}-${TOX_FEATURES}-win
+
+        - printenv
+
+        - cp .ci/choco.config $ChocolateyInstall/config/chocolatey.config
+        - powershell -c "Set-ExecutionPolicy -ExecutionPolicy Unrestricted
+                                             -Scope LocalMachine"
+
+        - python .ci/store_env_in_registry.py
+        - source .ci/refreshenv.sh
+
+        # TODO: Add support for disabling pre-installed vctools which is
+        # disabled in choco_requirements.  Uninstalling vctools fails
+      install:
+        - powershell -c ". .ci/Fudge.ps1 install"
+        - refreshenv
+        - taskkill -IM "gpg-agent.exe" || true
+      before_script:
+        - python --version
+        - cp tox.ini tox.orig
+        - "sed -i 's/^envlist.*$/envlist: '$TOXENV/ tox.ini"
+        - export TOX_SITEPACKAGES=true
+        - export VIRTUALENV_NO_PIP=1
+        - export VIRTUALENV_NO_SETUPTOOLS=1
+        - pip uninstall tox-venv || true
+      script:
+        - python -m tox --sitepackages
+      after_script:
+        - cp tox.orig tox.ini
+
+    - stage: test-other-versions
+      language: ruby
+      rvm: 2.5
+      env: DISABLE_BEARS=csvlint
+
+    - stage: test-other-versions
+      language: java
+      jdk: openjdk11
+      env: DISABLE_BEARS="languagetool tailor"
+    # openjdk10 and openjdk9 are broken on Travis
+    # https://github.com/travis-ci/travis-cookbooks/issues/976
+    # They need the same configuration as openjdk11:
+    # env: DISABLE_BEARS="languagetool tailor"
+    - stage: test-other-versions
+      language: java
+      jdk: openjdk7
+      env: DISABLE_BEARS=tailor
+
+    - stage: test-other-versions
+      language: generic
+      env: DIST=trusty BEARS=apt_get
+      addons:
+        apt:
+          packages:
+            - chktex
+            - cppcheck
+            - devscripts
+            - flawfinder
+            - indent
+            - libperl-critic-perl
+            - libxml2-utils
+            - mono-mcs
+            - php5-cli
+            - php-codesniffer
+            - shellcheck
+            - verilator
+
+    - stage: test-other-versions
+      language: generic
+      env: DIST=precise BEARS=apt_get
+      dist: precise
+      addons:
+        apt:
+          packages:
+            - chktex
+            - cppcheck
+            - devscripts
+            - flawfinder
+            - indent
+            - libperl-critic-perl
+            - libxml2-utils
+            - mono-mcs
+            - php5-cli
+            - python3
+            - verilator
 
     - python: 2.7
+      language: python
       stage: unsupported
       env: PIP_NO_COMPILE=1
       addons: false
@@ -52,14 +238,17 @@ jobs:
       before_script: true
       script: .ci/check_unsupported.sh
     - python: 3.3
+      language: python
       stage: unsupported
       env: PIP_NO_COMPILE=1
       addons: false
-      before_install: true
-      install: true
-      before_script: true
+      before_install: skip
+      install: skip
+      before_script: skip
       script: .ci/check_unsupported.sh
+
     - python: 3.6
+      language: python
       stage: moban
       addons: false
       cache: pip
@@ -70,65 +259,160 @@ jobs:
       after_success: false
       after_failure: false
       if: branch = master AND type = push
-    - *check_moban
+
+
+    # Entries generates from `supported_versions`
+    - stage: sentinel
+      language: python
+      python: 3.6
+      addons:
+        apt:
+          packages: clang-3.4
+
+    - stage: test-languages
+      language: python
+      python: 3.5
+      addons:
+        apt:
+          packages: clang-3.4
+
+    - stage: test-other-versions
+      language: python
+      python: 3.4.4
+      addons:
+        apt:
+          packages: clang-3.4
+
+    - stage: test-languages
+      language: csharp
+      mono: 5.20.1
+
+    - stage: test-languages
+      language: r
+      r: release
+
+    - stage: test-other-versions
+      language: r
+      r: devel
+
+    - stage: test-other-versions
+      language: r
+      r: oldrel
+
+    - stage: test-languages
+      language: node_js
+      node_js: '10'
+
+    - stage: test-other-versions
+      language: node_js
+      node_js: 9
+
+    - stage: test-other-versions
+      language: node_js
+      node_js: 8
+
+    - stage: test-other-versions
+      language: node_js
+      node_js: 7
+
+    - stage: test-other-versions
+      language: node_js
+      node_js: 6
+
+    - stage: test-languages
+      language: julia
+      julia: 1.1
+      env: JL_PKG=CoalaBears
+      install:
+        - julia --color=yes .ci/deps.julia.jl
+        # Verify compilation works
+        - julia -e 'import Lint.lintfile'
+
+    - stage: test-other-versions
+      language: julia
+      julia: 1.0
+      env: JL_PKG=CoalaBears
+      install:
+        - julia --color=yes .ci/deps.julia.jl
+        # Verify compilation works
+        - julia -e 'import Lint.lintfile'
+
+    - stage: test-other-versions
+      language: julia
+      julia: 0.7.0
+      env: JL_PKG=CoalaBears
+      install:
+        - julia --color=yes .ci/deps.julia.jl
+        # Verify compilation works
+        - julia -e 'import Lint.lintfile'
+
+    - stage: test-languages
+      language: dart
+      dart: 1.15.0
+
+    - stage: test-other-versions
+      language: dart
+      dart: 1.14.2
+
+    - stage: test-languages
+      language: perl
+      perl: 5.14
+
+    - stage: test-languages
+      language: go
+      go: 1.11
+      install: true
+
+    - stage: test-other-versions
+      language: go
+      go: '1.10'
+      install: true
+
+    - stage: test-languages
+      language: ruby
+      rvm: 2.4
+
+    - stage: test-other-versions
+      language: ruby
+      rvm: 2.3
+
+    - stage: test-other-versions
+      language: ruby
+      rvm: 2.2
+
+    - stage: test-other-versions
+      language: ruby
+      rvm: 2.1
+
+    - stage: test-languages
+      language: php
+      php: 7.2
+
+    - stage: test-other-versions
+      language: php
+      php: hhvm-3.18
+
+    - stage: test-other-versions
+      language: php
+      php: 5.5
+
+    - stage: test-languages
+      language: scala
+      scala: 2.11
+
+    - stage: test-other-versions
+      language: scala
+      scala: 2.12.2
+      jdk: openjdk8
+
+    - stage: test-languages
+      language: java
+      jdk: openjdk8
+
+
+    - *moban
   allow_failures:
-    - *check_moban
-
-dist: trusty
-
-.apt_sources: &apt_sources
-  - ubuntu-toolchain-r-test
-  # avsm  # OPAM stable
-  - hvr-ghc  # Haskell
-  - sourceline:  # R
-      deb https://cloud.r-project.org/bin/linux/ubuntu trusty-cran35/
-    key_url:
-      https://keyserver.ubuntu.com/pks/lookup?op=get&search=0x51716619E084DAB9
-  - sourceline:  # Julia
-      deb http://ppa.launchpad.net/staticfloat/juliareleases/ubuntu trusty main
-    key_url:
-      https://keyserver.ubuntu.com/pks/lookup?op=get&search=0xCF979FFA3D3D3ACC
-  - sourceline:  # astyle
-      deb http://ppa.launchpad.net/cs50/ppa/ubuntu trusty main
-    key_url:
-      https://keyserver.ubuntu.com/pks/lookup?op=get&search=0x5BDA2E974A0E822C
-
-addons:
-  apt:
-    sources: *apt_sources
-    packages:
-      - aspcud
-      - astyle
-      - cabal-install-1.24
-      - chktex
-      - clang-3.4
-      - cppcheck
-      - devscripts
-      - flawfinder
-      - gfortran
-      - ghc
-      - happy
-      - indent
-      - julia
-      - libarpack2
-      - libblas-dev
-      - libcolamd2.8.0
-      - libfftw3-3
-      - liblapack-dev
-      - libopenblas-base
-      - libpaper-utils
-      - libperl-critic-perl
-      - libumfpack5.6.2
-      - libxml2-utils
-      - luarocks
-      - mercurial
-      # menhir
-      - mono-mcs
-      # ocaml
-      # opam
-      - php-codesniffer
-      - r-base
-      - verilator
+    - *moban
 
 cache:
   pip: true
@@ -147,31 +431,68 @@ cache:
     # coala managed data
     - ~/nltk_data
     # Installed linters
+    # Check this version works
     - ~/infer-linux64-v$INFER_VERSION
     - ~/.local/
 
 env:
   global:
     - TERM=dumb
-    - R_LIB_USER=~/R/Library
+    - R_PROFILE=~/.Rprofile
     - LINTR_COMMENT_BOT=false
     - CABAL_VERSION=1.24
-    - INFER_VERSION=0.7.0
-    - PATH="$HOME/.local/bin:/opt/cabal/$CABAL_VERSION/bin:$PATH:$TRAVIS_BUILD_DIR/node_modules/.bin:$TRAVIS_BUILD_DIR/vendor/bin:$HOME/.cabal/bin:$HOME/infer-linux64-v$INFER_VERSION/infer/bin:$HOME/.local/tailor/tailor-latest/bin:$HOME/.luarocks/bin"
+    - PATH="$HOME/.local/bin:/opt/cabal/$CABAL_VERSION/bin:$PATH:$TRAVIS_BUILD_DIR/node_modules/.bin:$TRAVIS_BUILD_DIR/vendor/bin:$HOME/.cabal/bin:$HOME/.local/tailor/tailor-latest/bin:$HOME/.luarocks/bin"
+    # These are only needed by Windows
+    - NUGET_EXE_NO_PROMPT=true
+    - VIRTUALENV_NO_DOWNLOAD=1
+    # Enable to debug tox
+    - VIRTUALENV_VERBOSE=1
+    # This exceeds the travis maximum log length
+    # PIP_VERBOSE=1
+    - PIP_DISABLE_PIP_VERSION_CHECK=1
+    - PIP_YES=1
+    - FudgeCI=${TRAVIS_BUILD_DIR}/.ci/
+    - TOX_FEATURES=check-noskip-codecov
+
+stage: test
 
 before_install:
-  # Install latest stable version of Go using gimme
-  - gimme 1.11.5 > setup_go_root.sh
-  - source setup_go_root.sh
-  - nvm install 6.10.2
-  # Remove Ruby directive from Gemfile as this image has 2.2.5
-  - sed -i '/^ruby/d' Gemfile
-  - .ci/deps.sh
-  - .ci/deps.go.sh
-  - .ci/deps.cabal.sh
-  - .ci/deps.r.sh
-  # .ci/deps.opam.sh
-  - .ci/deps.java.sh
+  - printenv
+  - mkdir -p ~/bin ~/.local/bin
+
+  - if [ -z "$GOPATH" ]; then
+      export GOPATH="/home/travis/gopath";
+    fi
+  # TODO: implement DISABLE_BEARS globally, esp deps.generic.sh
+
+  - python --version
+  # ~/bin is uncached; ~/local/bin is cached; we dont want python/pip in latter
+  - rm -f ~/.local/bin/python* ~/.local/bin/pip*
+
+  - if [ -z "$TRAVIS_PYTHON_VERSION" ]; then
+      source .ci/deps.pyenv.sh;
+      source .ci/deps.python36.sh;
+    fi
+  - pyenv versions --bare
+  - if [ -z "$TRAVIS_PYTHON_VERSION" ]; then
+      PYTHON36_VERSION=$(pyenv versions --bare | fgrep '3.6' --max-count 1);
+      if [ "$BEARS" = "infer" -o "$BEARS" = "opam" ]; then
+        pyenv global 2.7 $PYTHON36_VERSION;
+      else
+        pyenv global $PYTHON36_VERSION;
+      fi;
+      hash -r;
+    fi
+  - if [ -z "$TRAVIS_PYTHON_VERSION" ]; then pyenv versions --bare; fi
+  - python --version
+  - if [ "${TRAVIS_PYTHON_VERSION/3.4/}" != "$TRAVIS_PYTHON_VERSION" ]; then
+      pip install pip==9.0.3 setuptools==21.2.2;
+    fi
+
+  - if [ -f .ci/deps.$TRAVIS_LANGUAGE.sh ]; then
+      bash -e -x .ci/deps.$TRAVIS_LANGUAGE.sh;
+    fi
+
   # https://github.com/coala/coala/issues/3183
   - cp requirements.txt requirements.orig
   - printf '%s\n%s\n%s\n'
@@ -182,22 +503,25 @@ before_install:
 
 before_script:
   - mv requirements.orig requirements.txt
-  - .ci/deps.coala-bears.sh
 
 script:
-  - python setup.py bdist_wheel
-  - pip install $(ls ./dist/*.whl)"[alldeps]"
-  # Ensure bear requirements are in sync with the bear PipRequirement
-  - .ci/generate_bear_requirements.py --check --update
-  - coala --non-interactive
-  - rm bears/java/InferBear.py tests/java/InferBearTest.py
-  - rm bears/go/GoReturnsBear.py tests/go/GoReturnsBearTest.py
-  - pytest
-  - codecov
-  - python setup.py docs
-
-notifications:
-  email: false
+  - if [ -z "$TRAVIS_PYTHON_VERSION" ]; then
+      python -m pip install --upgrade --user -r test-requirements.txt;
+    fi
+  # Ensure metadata files are in sync with the bear metadata in the source
+  - if [ -n "$TRAVIS_PYTHON_VERSION" ]; then
+      python setup.py bdist_wheel;
+      pip install $(ls ./dist/*.whl)"[alldeps]";
+      coala --non-interactive;
+      PYTHONPATH=. .ci/generate_bear_metadata.py --debug --update;
+    fi
+  - if [ "${TRAVIS_PYTHON_VERSION/3.4/}" != "$TRAVIS_PYTHON_VERSION" ]; then
+      pip install --upgrade setuptools;
+    fi
+  - python -m tox -vvv
+  - if [ -n "$TRAVIS_PYTHON_VERSION" ]; then
+      python setup.py docs;
+    fi
 
 branches:
   exclude:
